In [3]:
import numpy as np

In [124]:
#1

star_data = np.array([[2, 3, 5], [4, 6, 8], [11, 13, 17], [7, 10, 13]])

def containsPrimes(num):
    for i in range(2, int(np.sqrt(num))+1):
        if (num % i) == 0:
            return False
        else:
            return True

result = []
for row in star_data:
    if any (containsPrimes(num) for num in row):
        result.append(row)
prime_star_data = np.array(result)

prime_star_data

array([[ 2,  3,  5],
       [11, 13, 17],
       [ 7, 10, 13]])

In [125]:
#2.1

list = []
for i in range(1, 65):
    list.append(0)

checkerboard = np.array(list)
checkerboard.shape = (8, 8)

checkerboard

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [126]:
#2.2

checkerboard[0:8:2, 0:8:2] = 1

checkerboard

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [127]:
#2.3

checkerboard[1:8:2, 1:8:2] = 1

checkerboard

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [128]:
#2.4

newcheckerboard = np.array(list)
newcheckerboard.shape = (8, 8)

newcheckerboard[0:8:2, 1:8:2] = 1
newcheckerboard[1:8:2, 0:8:2] = 1

newcheckerboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [130]:
#3

universe = np.array(['galaxy', 'clusters'])

def expansion(stringarr, numspaces):
    newstringarr = []
    spaces = ""
    for n in range(0, numspaces):
        spaces += " "
    for i in range(0, len(stringarr)):
        newstr = ""
        currstring = stringarr[i]
        for j in range(0, len(currstring)):
            newstr += currstring[j]
            newstr += spaces
        newstringarr.append(newstr)
    return newstringarr

uni_expansion = expansion(universe, 3)
uni_expansion

['g   a   l   a   x   y   ', 'c   l   u   s   t   e   r   s   ']

In [131]:
#4

stars = np.random.randint(500, 2000, (5, 5))
sorted_stars = np.sort(stars)[::-1]
sorted_stars

array([[1122, 1164, 1245, 1639, 1657],
       [ 621,  738,  878, 1268, 1562],
       [ 713,  965, 1203, 1947, 1994],
       [1362, 1419, 1450, 1650, 1898],
       [1193, 1344, 1421, 1879, 1975]])

In [132]:
#4 continued

lowest = sorted_stars[0:5, 1:2]

lowest_stars = np.array(lowest)
lowest_stars

array([[1164],
       [ 738],
       [ 965],
       [1419],
       [1344]])