In [3]:
import numpy as np

In [90]:
#1

star_data = np.array([[2, 3, 5], [4, 6, 8], [11, 13, 17], [7, 10, 13]])
prime_star_data = np.array([])


# def containsPrimes(star_data):
#     count = 0
#     for list in range(len(star_data)):
#         for i in star_data[list]:
#             for j in range (1, i+1):
#                 if i%j == 0:
#                     count += 1
#             if count == 2:
#                  np.append(prime_star_data, list)
#     return(prime_star_data)

def containsPrimes(star_data):
    count = 0
    for i in star_data:
        for j in i:
            if j%i == 0:
                count += 1
        if count == 2:
                prime_star_data = np.append(prime_star_data, list)
    return(prime_star_data)





containsPrimes = containsPrimes(star_data)
containsPrimes

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [91]:
#2.1

list = []
for i in range(1, 65):
    list.append(0)

checkerboard = np.array(list)
checkerboard.shape = (8, 8)

checkerboard

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [82]:
#2.2

checkerboard[0:8:2, 0:8:2] = 1

checkerboard

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [67]:
#2.3

checkerboard[1:8:2, 1:8:2] = 1

checkerboard

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [88]:
#2.4

newcheckerboard = np.array(list)
newcheckerboard.shape = (8, 8)

newcheckerboard[0:8:2, 1:8:2] = 1
newcheckerboard[1:8:2, 0:8:2] = 1

newcheckerboard

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [43]:
#3

universe = np.array(['galaxy', 'clusters'])

def expansion(stringarr, numspaces):
    newstringarr = []
    spaces = ""
    for n in range(0, numspaces):
        spaces += " "
    for i in range(0, len(stringarr)):
        newstr = ""
        currstring = stringarr[i]
        for j in range(0, len(currstring)):
            newstr += currstring[j]
            newstr += spaces
        newstringarr.append(newstr)
    return newstringarr

uni_expansion = expansion(universe, 2)
uni_expansion

['g  a  l  a  x  y  ', 'c  l  u  s  t  e  r  s  ']

In [110]:
#4

stars = np.random.randint(500, 2000, (5, 5))
sorted_stars = np.sort(stars)[::-1]

lowest = sorted_stars[0:5, 1:2]

lowest_stars = np.array(lowest)
lowest_stars

[[ 916 1372 1808 1927 1998]
 [ 905 1096 1274 1855 1910]
 [ 560  601  930  947 1970]
 [ 707 1288 1389 1618 1954]
 [ 508  788 1257 1344 1925]]


array([[1372],
       [1096],
       [ 601],
       [1288],
       [ 788]])